version: '3.3'
services:
  web:
    build:
      context: .
    restart: always
    ports:
      - "10177:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - bacabaca/.env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network
    platform: linux/amd64

  web2:
    build:
      context: .
    restart: always
    ports:
      - "10178:2020"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - bacabaca/.env.app2
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network
    platform: linux/amd64

  db:
    image: postgres:14-alpine
    ports:
      - '15177:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge